### ISSUE TITLE
error ?

### ISSUE THREAD

**Issue by chocosando** [cbellei/word2veclite#1]
Thank you for great codes!

My environment is pip3, ubuntu, ... I completed all libs ..

But, I got an error in last command line:

>>> 
>>> W1, W2, loss_vs_epoch = cbow.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'run'
>>> 

Would you help me ?

Regards,

**Comment by cbellei** [comment]
Hi @chocosando,
I just tested the example again and it works. If you do `import word2veclite`, does this give you any problems?

**Comment by chocosando** [comment]
Hello, 
There is no error in "import word2veclite" 

My error is similar to second issue: 
"ValueError: shapes (2,7) and (2,7) not aligned: 7 (dim 1) != 2 (dim 0)" 

My version of numpy is 1.14.2 .  Should I use 1.13 version ?

**Comment by cbellei** [comment]
Yes, I would just do a `pip install -r requirements.txt` and you should be good to go.

**Comment by chocosando** [comment]
Thank you so much!
It works well. : )

**Comment by cbellei** [comment]
Great, I am going to close this issue then!
